[project]
name = "py-flask"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "flask==3.1.2",
    "inngest==0.5.16",
    "mypy==1.17.1",
    "python-dotenv==1.1.1",
    "ruff==0.12.12",
    "structlog==25.4.0",
]
