[project]
name = "py-fastapi"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.116.1",
    "inngest==0.5.15",
    "mypy==1.17.1",
    "python-dotenv==1.1.1",
    "ruff==0.12.12",
    "structlog==25.4.0",
    "uvicorn==0.35.0",
]
